// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjhrkljsrkyjqhtwgubq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaHJrbGpzcmt5anFodHdndWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzY5NjEsImV4cCI6MjA2Njg1Mjk2MX0.CCLG34Ias-T_nMYQQB68HUoXiS34rVEo2aFsoxofVHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});